version: '3.4'

services:
  gateway-api:
    image: gateway-api
    depends_on:
      rabbitmq:
        condition: service_healthy
      customer.api:
        condition: service_started
      db:
        condition: service_started
    build:
      context: src/
      dockerfile: Gateway/Gateway.Api/Dockerfile
    ports:
      - 5555:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    links:
      - customer-api

  customer-api:
    image: customer-api
    depends_on:
      - db
    build:
      context: src/
      dockerfile: Customer/Customer.Api/Dockerfile
    ports:
      - 5010:80
    environment:
      - ASPNETCORE_ConnectionStrings__SqlServer=Server=db;Database=customer;User Id=sa;Password=Passw@rd;Encrypt=false
      - ASPNETCORE_ENVIRONMENT=Production
    links:
      - db

  customer-worker:
    image: customer-worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
    build:
      context: src/
      dockerfile: Customer/Customer.Worker/Dockerfile
    environment:
      - DOTNET_ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672/
      - DOTNET_ConnectionStrings__SqlServer=Server=db;Database=customer;User Id=sa;Password=Passw@rd;Encrypt=false
      - DOTNET_Messaging__InputQueue=customer-input
    links:
      - db
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 30s
        timeout: 30s
        retries: 3

  db:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    container_name: 'db'
    environment:
       - ACCEPT_EULA="Y"
       - MSSQL_SA_PASSWORD=Passw@rd
       - MSSQL_PID=Developer
       - MSSQL_DB=events_service
       - MSSQL_USER=SA
       - MSSQL_PASSWORD=Passw@rd
       - MSSQL_DB_AUDIT_LOG=events_service_audit_log
  
    ports:
       - 1433:1433
    volumes:
       - ~/.docker-conf/mssql/data/:/var/opt/mssql/data
       - ~/.docker-conf/mssql/log/:/var/opt/mssql/log

