version: '3.4'

services:
  customer.api:
    image: ${DOCKER_REGISTRY-}customer.api
    build:
      context: src/
      dockerfile: Customer/Customer.Api/Dockerfile
    ports:
      - 5010:80
    environment:
      - DOTNET_ConnectionStrings__SqlServer=Server=localhost;Database=customer;User Id=sa;Password=Passw@rd;Encrypted=False

  customer.worker:
    image: ${DOCKER_REGISTRY-}customer.worker
    build:
      context: src/
      dockerfile: Customer/Customer.Worker/Dockerfile
    environment:
      - DOTNET_ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672/
      - DOTNET_ConnectionStrings__SqlServer=Server=localhost;Database=customer;User Id=sa;Password=Passw@rd;Encrypted=False
      - DOTNET_Messaging__InputQueue=customer-input
  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  db:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    container_name: 'db'
    environment:
       - ACCEPT_EULA="Y"
       - MSSQL_SA_PASSWORD=Passw@rd
       - MSSQL_PID=Developer
       - MSSQL_DB=events_service
       - MSSQL_USER=SA
       - MSSQL_PASSWORD=Passw@rd
       - MSSQL_DB_AUDIT_LOG=events_service_audit_log
    ports:
       - 1433:1433
    volumes:
       - ~/.docker-conf/mssql/data/:/var/opt/mssql/data
       - ~/.docker-conf/mssql/log/:/var/opt/mssql/log

