version: '3.4'

services:
  customer.api:
    image: ${DOCKER_REGISTRY-}customer.api
    build:
      context: src/Customer/Customer.Api/
      dockerfile: Dockerfile
    ports:
      - 5010:80

  customer.worker:
    image: ${DOCKER_REGISTRY-}customer.worker
    build:
      context: src/Customer/Customer.Worker/
      dockerfile: Dockerfile
  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    

