/*
 * Customer.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Customer.ApiClient.Client;
using Customer.ApiClient.Api;
// uncomment below to import models
//using Customer.ApiClient.Model;

namespace Customer.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing CustomerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CustomerApiTests : IDisposable
    {
        private CustomerApi instance;

        public CustomerApiTests()
        {
            instance = new CustomerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CustomerApi
            //Assert.IsType<CustomerApi>(instance);
        }

        /// <summary>
        /// Test GetCustomerById
        /// </summary>
        [Fact]
        public void GetCustomerByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetCustomerById(id);
            //Assert.IsType<CustomerModel>(response);
        }

        /// <summary>
        /// Test ListAllCustomers
        /// </summary>
        [Fact]
        public void ListAllCustomersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListAllCustomers();
            //Assert.IsType<List<CustomerModel>>(response);
        }
    }
}
