/*
 * Customer.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Customer.ApiClient.Api;
using Customer.ApiClient.Model;
using Customer.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Customer.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerModel
        //private CustomerModel instance;

        public CustomerModelTests()
        {
            // TODO uncomment below to create an instance of CustomerModel
            //instance = new CustomerModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerModel
        /// </summary>
        [Fact]
        public void CustomerModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerModel
            //Assert.IsType<CustomerModel>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
