name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  acr-login:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
      # Container registry username
        username: ${{ secrets.ACR_USERNAME }}
      # Container registry password
        password: ${{ secrets.ACR_PASSWORD }}
      # Container registry server url
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
  build-worker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Customer Worker Docker image
      run: docker build . --file /src/Customer/Customer.Worker/Dockerfile --tag customer/customer.worker:dev-$(date +%s)
  build-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Customer Worker Docker image
      run: docker build . --file /src/Customer/Customer.Api/Dockerfile --tag customer/customer.api:dev-$(date +%s)
  acr_push:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
 
