name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x'
    - name: Restore dependencies
      run: dotnet restore test/Customer.Tests.Unit/Customer.Tests.Unit.csproj
    - name: Build
      run: dotnet build test/Customer.Tests.Unit/Customer.Tests.Unit.csproj --no-restore
    - name: Test
      run: dotnet test test/Customer.Tests.Unit/Customer.Tests.Unit.csproj
